### PR TITLE
Add Kevin Dunglas

### PR DESCRIPTION
**Pull request by SebLevDev**

### CODE REVIEW

**Comment by mykiwi** [comment]
I will wait a little bit more since this photo don't match the slides: https://twitter.com/richcongress/status/1111289193194504192
But :+1:

**Comment by mykiwi** [comment]
ping @dunglas

**Comment by Aylarius** [comment]
I believe this is the right link to the slides: https://www.slideshare.net/coopTilleuls/symfony-on-steroids-vuejs-mercure-panther-138627741

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
